// ifndef::snippets[]
// :snippets: ./build/generated-snippets
// endif::[]
= Hello,GSM API 명세서
양시준, <yangsijun5528@gmail.com>
v0.1, 2023-06-16
:doctype: book
:icons: font
:source-highlighter: rouge
:description: this is specific of Hello,GSM
:toc: left
:toc-title: Index
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Curl request
:operation-http-request-title: HTTP request
:operation-http-response-title: HTTP response
:operation-httpie-request-title: HTTPie request
:operation-links-title: Links
:operation-request-body-title: Request body
:operation-request-fields-title: Request fields
:operation-response-body-title: Response body
:operation-response-fields-title: Response fields

== 개요
이 API문서는 'Hello,GSM' 프로젝트의 산출물입니다.

해당 문서는 AsciiDoc 포맷으로 작성되었습니다.

AsciiDoc 문법에 관한 내용은 link:https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference[AsciiDoc Syntax Quick Reference]를 참고하시길 바랍니다.

``API 명세``까지 아래 내용은 포멧을 보여주기 위한 임시 내용입니다. Hello,GSM의 명세가 아닙니다.

== API 서버 경로
[cols="2,5,3"]
|====
|환경         |DNS |비고
|개발(dev)    | link:[https://dev-api.hellogsm.kr] |API 문서 제공
|운영(prod)   | link:[https://api.hellogsm.kr] | API 문서 미제공
|====

NOTE: 해당 프로젝트 API문서는 개발환경까지 노출되는 것을 권장합니다.

CAUTION: 운영환경에 노출될 경우 보안 관련 문제가 발생할 수 있습니다.

=== 응답형식
프로젝트는 다음과 같은 응답형식을 제공합니다.

==== 정상(200, OK)

|====
|응답데이터가 없는 경우|응답데이터가 있는 경우

a|[source,json]
----
{
    "code": "0000", // 정상인 경우 '0000'
    "message": "OK", // 정상인 경우 'OK'
    "data": null
}
----

a|[source,json]
----
{
    "code": "0000", // 정상인 경우 '0000'
    "message": "OK", // 정상인 경우 'OK'
    "data": {
        "name": "honeymon-enterprise"
    }
}
----
|====

==== 상태코드(HttpStatus)
응답시 다음과 같은 응답상태 헤더, 응답코드 및 응답메시지를 제공합니다.

[cols="3,1,3,3"]
|====
|HttpStatus |코드 |메시지 |설명

|`OK(200)` |`0000` |"OK" |정상 응답
|`INTERNAL_SERVER_ERROR(500)`|`S5XX` |"알 수 없는 에러가 발생했습니다. 관리자에게 문의하세요." |서버 내부 오류
|`FORBIDDEN(403)`|`C403` |"[AccessDenied] 잘못된 접근입니다." |비인가 접속입니다.
|`BAD_REQUEST(400)`|`C400` |"잘못된 요청입니다. 요청내용을 확인하세요." |요청값 누락 혹은 잘못된 기입
|`NOT_FOUND(404)`|`C404` |"상황에 따라 다름" |요청값 누락 혹은 잘못된 기입

|====

= API 명세

== 회원(User)
회원의 인증 정보(id, 권한 등)를 조회할 수 있습니다.

=== ID로 USER 조회
ID로 USER를 조회합니다.

WARNING: `userId` 를 입력해야만 합니다.

==== Request
operation::user/find-by-user-id[snippets='curl-request,httpie-request,http-request,path-parameters']

==== Response
operation::user/find-by-user-id[snippets='http-response,response-fields']

=== 인증된 USER 조회
현재 인증되어있는 회원을 조회합니다.

==== Request
operation::user/find-by-authenticated[snippets='curl-request,httpie-request,http-request,request-headers']

==== Response
operation::user/find-by-authenticated[snippets='http-response,response-fields']

== 신원(Identity)
회원의 본인인증 정보(실명, 전화번호)를 생성,조회 할 수 있습니다.

=== ID로 IDENTITY 조회
ID로  IDENTITY를 조회합니다.

WARNING: `userId` 를 입력해야만 합니다.

==== Request
operation::identity/find-by-user-id[snippets='curl-request,httpie-request,http-request,path-parameters']

==== Response
operation::identity/find-by-user-id[snippets='http-response,response-fields']

=== 인증 중인 정보로 IDENTITY 조회
현재 인증되어있는 사용자 정보로 신원을 조회합니다.

==== Request
operation::identity/find-by-authenticated[snippets='curl-request,httpie-request,http-request,request-headers']

==== Response
operation::identity/find-by-authenticated[snippets='http-response,response-fields']

=== 인증 중인 정보로 IDENTITY 생성
현재 인증되어있는 사용자 정보로 신원을 생성합니다.

사용자의 개인정보(본인인증 정보)를 등록하고 권한을 `인증된 유저(ROLE_USER)` 로 변경합니다.

==== Request
operation::identity/create-by-authenticated[snippets='curl-request,httpie-request,http-request,request-body']

==== Response
사용자의 권한이 업데이트되어 세션 정보를 갱신하기 위해 로그아웃 URI로 리다이렉트됩니다.

operation::identity/create-by-authenticated[snippets='http-response']
