drop table if exists admission_grade cascade;
    

drop table if exists admission_info cascade;
    

drop table if exists admission_status cascade;
    

drop table if exists application cascade;
    

drop table if exists ged_admission_grade cascade;
    

drop table if exists graduate_admission_grade cascade;
    

drop table if exists `identity` cascade;
    

drop table if exists middle_school_grade cascade;
    

drop table if exists `user` cascade;
    

create table admission_grade (
                                 admission_grade_id bigint generated by default as identity,
                                 dtype varchar(31) not null,
                                 percentile_rank numeric(38,2) not null,
                                 total_score numeric(38,2) not null,
                                 primary key (admission_grade_id)
);
    

create table admission_info (
                                admission_info_id bigint generated by default as identity,
                                address varchar(255) not null,
                                applicant_birth date not null,
                                applicant_gender varchar(255) not null,
                                applicant_image_uri varchar(255) not null,
                                applicant_name varchar(255) not null,
                                applicant_phone_number varchar(255) not null,
                                first_desired_major varchar(255) not null,
                                second_desired_major varchar(255) not null,
                                third_desired_major varchar(255) not null,
                                detail_address varchar(255) not null,
                                graduation varchar(255) not null,
                                guardian_name varchar(255) not null,
                                guardian_phone_number varchar(255) not null,
                                relation_with_applicant varchar(255) not null,
                                school_location varchar(255),
                                school_name varchar(255),
                                screening varchar(255) not null,
                                teacher_name varchar(255),
                                teacher_phone_number varchar(255),
                                telephone varchar(255),
                                primary key (admission_info_id)
);
    

create table admission_status (
                                  application_status_id bigint generated by default as identity,
                                  final_major varchar(255),
                                  first_evaluation varchar(255) not null,
                                  is_final_submitted boolean not null,
                                  is_prints_arrived boolean not null,
                                  registration_number bigint,
                                  screening_first_evaluation_at varchar(255),
                                  screening_second_evaluation_at varchar(255),
                                  screening_submitted_at varchar(255),
                                  second_evaluation varchar(255) not null,
                                  second_score numeric(38,2),
                                  primary key (application_status_id)
);
    

create table application (
                             application_id bigint generated by default as identity,
                             user_id bigint not null,
                             admission_grade_admission_grade_id bigint not null,
                             admission_info_admission_info_id bigint not null,
                             admission_status_application_status_id bigint not null,
                             middle_school_grade_middle_school_grade_id bigint not null,
                             primary key (application_id)
);
    

create table ged_admission_grade (
                                     ged_max_score numeric(38,2) not null,
                                     ged_total_score numeric(38,2) not null,
                                     admission_grade_id bigint not null,
                                     primary key (admission_grade_id)
);
    

create table graduate_admission_grade (
                                          artistic_score numeric(38,2) not null,
                                          attendance_score numeric(38,2) not null,
                                          curricular_subtotal_score numeric(38,2) not null,
                                          extracurricular_subtotal_score numeric(38,2) not null,
                                          grade_1_semester_1_score numeric(38,2) not null,
                                          grade_1_semester_2_score numeric(38,2) not null,
                                          grade_2_semester_1_score numeric(38,2) not null,
                                          grade_2_semester_2_score numeric(38,2) not null,
                                          grade_3_semester_1_score numeric(38,2) not null,
                                          volunteer_score numeric(38,2) not null,
                                          admission_grade_id bigint not null,
                                          primary key (admission_grade_id)
);
    

create table `identity` (
                          identity_id bigint generated by default as identity,
                          birth date,
                          gender varchar(255),
                          name varchar(255),
                          phone_number varchar(255),
                          user_id bigint,
                          primary key (identity_id)
);
    

create table middle_school_grade (
                                     middle_school_grade_id bigint generated by default as identity,
                                     middle_school_grade_text clob not null,
                                     primary key (middle_school_grade_id)
);
    

create table `user` (
                        user_id bigint generated by default as identity,
                        provider varchar(255),
                        provider_id varchar(255),
                        role varchar(255),
                        primary key (user_id)
);
    

alter table if exists application
    add constraint UK_5heq93474271p9oo8kw241xin unique (admission_grade_admission_grade_id);
    

alter table if exists application
    add constraint UK_1xj1p12axsq5gn93ehqi3lhkd unique (admission_info_admission_info_id);
    

alter table if exists application
    add constraint UK_1ud1g0ic8yy4oejuwsnb1fsl unique (admission_status_application_status_id);
    

alter table if exists application
    add constraint UK_aai80sffoev9prh4sobp1dsv0 unique (middle_school_grade_middle_school_grade_id);
    

alter table if exists identity
    add constraint UK_gi5aydpad5j0hnvjrfv1716rv unique (user_id);
    

alter table if exists application
    add constraint FKd48h9nauv1h4xrj0ff0atgqa6
    foreign key (admission_grade_admission_grade_id)
    references admission_grade;
    

alter table if exists application
    add constraint FKjnmbnoxqeb8wewmkgr8wse110
    foreign key (admission_info_admission_info_id)
    references admission_info;
    

alter table if exists application
    add constraint FKmwo9jkmmpkdife010tpet7jmk
    foreign key (admission_status_application_status_id)
    references admission_status;
    

alter table if exists application
    add constraint FKhkudn347wywhah32w0krlv1ra
    foreign key (middle_school_grade_middle_school_grade_id)
    references middle_school_grade;
    

alter table if exists ged_admission_grade
    add constraint FK2asiis6e245fywnys8mqpvcge
    foreign key (admission_grade_id)
    references admission_grade;
    

alter table if exists graduate_admission_grade
    add constraint FK7lt9oxq2aab7fp75t5uj5xh3k
    foreign key (admission_grade_id)
    references admission_grade;
